export const SET_LOADING = "SET_LOADING";
export const AJOUT_ANNONCE_SUCCESS = "AJOUT_ANNONCE_SUCCESS";
export const AJOUT_FAIL = "AJOUT_FAIL";


export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_SUCCESS="GET_ALL_POSTS_SUCCESS";

export const PRODUCT_DETAIL_SUCCESS="PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL="PRODUCT_DETAIL_FAIL"

export const PRODUCT_UPDATE_SUCCESS="PRODUCT_UPDATE_SUCCESS"
export const PRODUCT_UPDATE_FAIL="PRODUCT_UPDATE_FAIL"